apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scim-api.fullname" . }}
  labels:
    {{- include "scim-api.labels" . | nindent 4 }}
spec:
  replicas: {{ index .Values "scim-server" "replicaCount" }}
  selector:
    matchLabels:
      {{- include "scim-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scim-api.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- $scim := index .Values "scim-server" | default (dict) }}
      {{- with (index $scim "image" | default (dict)) }}
      {{- if .pullSecrets }}
      imagePullSecrets:
        {{- toYaml .pullSecrets | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "scim-api.name" . }}
          image: "{{ (index $scim "image").repository }}:{{ (index $scim "image").tag }}"
          imagePullPolicy: {{ (index $scim "image").pullPolicy }}
          ports:
            - name: http
              containerPort: {{ (index $scim "port") | default .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "scim-api.fullname" . }}
            - secretRef:
                name: {{ .Values.secret.name }}
          {{- if .Values.probe.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
          {{- end }}
          {{- if .Values.probe.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
          {{- end }}
          {{- with (index $scim "resources") }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
