apiVersion: v2
name: scim-api
description: A Helm chart for deploying the Node.js based SCIM API
home: https://github.com/yuvalherziger/node-scim-api
maintainers:
  - name: Yuval Herziger
    url: https://github.com/yuvalherziger/node-scim-api
keywords:
  - node
  - scim
  - api
  - kubernetes
  - helm
sources:
  - https://github.com/yuvalherziger/node-scim-api
kubeVersion: ">=1.22.0-0"
type: application
version: 0.5.1
appVersion: "latest"
